name: Sending the release of the without-payment-for-woocommerce plugin to SVN WordPress
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  job_1:
    name: Deploy new plugin version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Composer run
        run: composer install
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: without-payment-for-woocommerce # имя репозитория
